### ISSUE TITLE
MiningUtils required Files update

### ISSUE THREAD

**Issue by OkamiRyu92** [TheMillman/MiningUtils#1]
Hello, configuration files for this mod needs to be updated to allow for 1.19.3-0.2.0 as is seen in FarmingUtils, otherwise will not allow the use of TheMillmanLib. If I try to downgrade it kicks farmingutils as an allowed mod, if I upgrade to the .2.0 then it kicks out miningutils, even though it should be considered "Greater" but it's not.

**Comment by TheMillman** [comment]
I'll fix everything by tomorrow, unfortunately I'm not at home now.

**Comment by TheMillman** [comment]
Are you sure you have the latest version of all 3 mods installed? I just tried it and it works fine for me.
The latest versions are:
The MillmanLib: 1.19.3-0.2.0
Farming Utils: 1.19.3-0.1.8
Mining Utils: 1.19.3-1.1.1

**Comment by OkamiRyu92** [comment]
Ah that would explain it, I'm using forge and it didn't show the beta update, i'll try that and see if that works for the mining utils
